# Generated by Django 4.2.4 on 2023-11-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProjects', '0004_alter_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='projekt',
            name='website',
            field=models.TextField(blank=True, null=True),
        ),
    ]
