# Generated by Django 4.2.4 on 2023-11-30 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myProjects', '0005_projekt_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projekt',
            name='plot_1',
        ),
        migrations.RemoveField(
            model_name='projekt',
            name='plot_2',
        ),
        migrations.RemoveField(
            model_name='projekt',
            name='plot_3',
        ),
        migrations.RemoveField(
            model_name='projekt',
            name='plot_4',
        ),
        migrations.RemoveField(
            model_name='projekt',
            name='plot_5',
        ),
        migrations.RemoveField(
            model_name='projekt',
            name='website',
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myProjects.projekt')),
            ],
        ),
    ]
