# Generated by Django 4.2.4 on 2023-12-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProjects', '0007_rename_image_4_blog_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projekt',
            name='github_link',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
