# Generated by Django 4.2.4 on 2023-12-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProjects', '0009_delete_blog_projekt_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interessen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interesse', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='projekt',
            name='skills',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
