# Generated by Django 4.2.4 on 2023-12-10 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myProjects', '0010_interessen_alter_projekt_skills'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interessen',
        ),
    ]
