# Generated by Django 4.2.4 on 2023-12-11 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myProjects', '0012_projekt_image_4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projekt',
            name='structure',
        ),
    ]
